sudo: false
language: node_js
node_js:
  - 10
  - 12
  - 14

before_install:
  - npm config set depth 0
before_script:
  - 'if [ "${ESLINT-}" == "6" ]; then npm install --no-save "eslint@${ESLINT}.1" ; fi'
  - 'if [ "${ESLINT-}" == "5" ]; then npm install --no-save "eslint@${ESLINT}" mocha@6.2.2 eslint-plugin-unicorn@8.0.2 @typescript-eslint/parser@1.13.0 ; fi'
script:
  - npm run test
  - 'if [ -n "${LINT-}" ]; then npm run eslint; fi'
env:
  matrix:
    - ESLINT=6
    - ESLINT=5
matrix:
  fast_finish: true
  include:
    - node_js: 'lts/*'
      env: LINT=true
  exclude:
    - node_js: 6
      env: ESLINT=6
